Для отображения описания исключения в Java вы можете воспользоваться
методом getMessage() класса Throwable.
Метод getMessage() возвращает строку, которая содержит описание исключения.

Вот как это можно сделать:
try {
    // Код, который может вызвать исключение
    int result = 10 / 0; // Приведет к ArithmeticException
} catch (ArithmeticException e) {
    // Обработка исключения ArithmeticException
    System.out.println("Произошла ошибка: " + e.getMessage());
}
В этом примере, если произойдет деление на ноль и возникнет исключение ArithmeticException,
метод getMessage() будет использован для получения описания ошибки,
и это описание будет выведено на консоль.

Обратите внимание, что сообщение об ошибке зависит от типа исключения и может быть
предоставлено или не предоставлено внутри самого исключения.
Поэтому не все исключения будут иметь описания, и вам может потребоваться дополнительная
информация для понимания сути ошибки, такая как стек вызовов (stack trace).
Вы можете использовать метод printStackTrace() класса Throwable,
чтобы вывести стек вызовов и подробную информацию об исключении:
try {
    // Код, который может вызвать исключение
    int result = 10 / 0; // Приведет к ArithmeticException
} catch (ArithmeticException e) {
    // Обработка исключения ArithmeticException
    System.out.println("Произошла ошибка: " + e.getMessage());
    e.printStackTrace();
}
Метод printStackTrace() выведет не только описание исключения, но и информацию о месте,
где произошла ошибка, и стек вызовов до этого места. Это может помочь вам лучше понять,
как и почему возникла ошибка.





